openapi: 3.0.2
info:
  title: Connect 2.0 Inbound API Documents
  version: '6.5'
servers:
  - url: https://erpuat2.superprocure.com
paths:
  /api/masters/customerMaster/v1:
    post:
      security:
        - BasicAuth: []
      tags:
        - Master
      summary: 'Customer Master : IN_API_003'
      description: >-
        **API ID** :- IN_API_003


        Customer Master API allows seamless integration between systems by
        providing essential information about customers. It offers a
        comprehensive range of details pertaining to customers, including their
        unique identification code, location, contact information, regional
        categorization, and billing and shipping codes.

                
        **Provider:** SuperProcure 


        **Data Sender:** Client SAP


        **Data Receiver:** SuperProcure


        **Trigger & Action:** Customer Master API can be triggered during
        creation, modification, or retrieval of customer-related information.
        When the Customer Master API is triggered, it performs the action of
        retrieving customer-related information from the SAP system.


        **Outcome:** The API ensures that customer data remains synchronized
        between SAP and TMS to help maintain accurate and consistent customer
        data across both systems.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - customerData
              properties:
                customerData:
                  type: array
                  items:
                    type: object
                    required:
                      - customerCode
                      - customerName
                      - branchLongName
                      - branchShortName
                      - address
                      - city
                      - district
                      - state
                      - country
                      - pin
                      - isActive
                      - partyType
                      - contactPersonDetails
                    properties:
                      customerCode:
                        type: string
                        example: C245
                        description: Unique identifier assigned to each customer
                        minLength: 1
                        maxLength: 45
                      customerName:
                        type: string
                        example: User Name
                        description: >-
                          Represents the name or the official title associated
                          with the customer entity
                        minLength: 1
                        maxLength: 255
                      branchLongName:
                        type: string
                        example: AKHIL TRADERS
                        minLength: 1
                        maxLength: 255
                        description: ''
                      branchShortName:
                        type: string
                        example: AKHIL TRAD
                        description: ''
                        minLength: 1
                        maxLength: 255
                      address:
                        type: string
                        example: 144, LR Road, New Delhi-10023
                        description: >-
                          Physical location details of an entity, such as a
                          customer, vendor, or business partner
                        minLength: 1
                        maxLength: 255
                      city:
                        type: string
                        example: Kanpur
                        description: >-
                          Specific urban area where the customer is based or
                          where the business operates
                        minLength: 1
                        maxLength: 255
                      district:
                        type: string
                        example: Kanpur
                        description: >-
                          Used to categorize and organize customer, vendor, or
                          organizational data based on specific locations or
                          districts
                        minLength: 1
                        maxLength: 50
                      state:
                        type: string
                        example: UP
                        description: >-
                          Used to indicate the state, province, or similar
                          administrative division of a customer's or business
                          partner's location
                        minLength: 1
                        maxLength: 100
                      country:
                        type: string
                        example: India
                        description: Specific geographical region or nation
                        minLength: 1
                        maxLength: 2
                        default: IN
                      pin:
                        type: string
                        example: '700055'
                        description: >-
                          Numeric code used to identify specific postal areas or
                          regions
                        minLength: 1
                        maxLength: 45
                      pan_Name:
                        type: string
                        example: ABCD2871E
                        description: >-
                          Unique Permanent Account Number (PAN) assigned to an
                          individual or entity for taxation purposes
                        minLength: 0
                        maxLength: 45
                      tan_Number:
                        type: string
                        example: AAACB1234F
                        description: >-
                          TAN (Tax Deduction and Collection Account Number) is a
                          unique alphanumeric identifier assigned to entities or
                          individuals who are required to deduct or collect tax
                          at source
                        minLength: 0
                        maxLength: 45
                      gst_Number:
                        type: string
                        example: GST123456
                        description: >-
                          Unique identifier assigned by tax authorities to track
                          and regulate the GST-related transactions of a
                          business entity
                        minLength: 0
                        maxLength: 45
                      accountNumber:
                        type: string
                        example: '28820005686'
                        description: >-
                          Bank account number of any bank respective to the
                          customer
                        minLength: 0
                        maxLength: 255
                      ifscCode:
                        type: string
                        example: SBI0003122
                        description: >-
                          IFSC Code associated with the bank account number 
                          respective to the customer
                        minLength: 0
                        maxLength: 255
                      bankName:
                        type: string
                        example: SBI
                        description: >-
                          Name of the customer bank whose account number is
                          provided 
                        minLength: 0
                        maxLength: 255
                      isActive:
                        type: boolean
                        example: true
                        description: >-
                          Flag or indicator that signifies the current active
                          status of a particular entity, such as a customer,
                          vendor, or employee
                        enum:
                          - true
                          - false
                      partyType:
                        type: string
                        example: C/S
                        description: >-
                          Identifies the type of party involved, such as
                          customers, vendors, employees, partners, or other
                          relevant entities
                        minLength: 0
                        maxLength: 1
                        enum:
                          - C
                          - S
                      contactPersonDetails:
                        type: array
                        items:
                          type: object
                          required:
                            - contactPerson
                            - mobileNumber
                          properties:
                            contactPerson:
                              type: string
                              example: Ramesh
                              description: >-
                                Individual associated with a customer or vendor
                                who serves as the primary point of contact
                              minLength: 1
                              maxLength: 255
                            mobileNumber:
                              type: string
                              example: '9812345678'
                              description: >-
                                Contact phone number associated with a customer
                                or user
                              minLength: 1
                              maxLength: 255
                            email:
                              type: string
                              example: user@email.com
                              description: Email id associated with a customer or user
                              minLength: 0
                              maxLength: 255
                      kamPersonDetails:
                        type: array
                        items:
                          type: object
                          required:
                            - contactPerson
                            - mobileNumber
                          properties:
                            contactPerson:
                              type: string
                              example: Ramesh
                              description: >-
                                Key Account Manager (KAM) is a role responsible
                                for managing relationships with key customers
                              minLength: 1
                              maxLength: 255
                            mobileNumber:
                              type: string
                              example: '9812345678'
                              description: >-
                                Contact phone number associated with a Key
                                Account Manager
                              minLength: 1
                              maxLength: 255
                            email:
                              type: string
                              example: user@email.com
                              description: Email id associated with a Key Account Manager
                              minLength: 0
                              maxLength: 255
          application/xml:
            schema:
              $ref: '#/components/schemas/customerData'
      responses:
        '201':
          description: Successful
          content:
            application/json:
              schema:
                required:
                  - message
                  - statusCode
                  - status
                properties:
                  message:
                    type: string
                    example: Customer Master Created Successfully
                  statusCode:
                    type: string
                    example: '201'
                  status:
                    type: string
                    example: success
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
        '500':
          description: Internal server Error
                  
tags:
  - name: Master

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    customerData:
      type: object
      properties:
        customerCode:
          type: string
          example: CARR009
        customerName:
          type: string
          example: RAYCHEM RPG PVT. LIMITED
        branchLongName:
          type: string
          example: AKHIL TRADERS
          description: ''
        branchShortName:
          type: string
          example: AKHIL TRAD
          description: ''
        address:
          type: string
          example: >-
            TRANSFORMER - MFG - CHAKAN GAT NO.426 / 2B, CHAKAN-TALEGAON ROAD
            OPP. BAJAJ AUTO MATERIAL GATE MAHALUNGE VILLAGE, TAL: KHED
        city:
          type: string
          example: KHED
        district:
          type: string
          example: Pune
        state:
          type: string
          example: Maharashtra
        country:
          type: string
          example: India
        pin:
          type: string
          example: '401501'
        accountNumber:
          type: string
          example: '28820005686'
        ifscCode:
          type: string
          example: SBI0003126
        bankName:
          type: string
          example: SBI
        isActive:
          type: boolean
          example: 'true'
        transportationZone:
          type: string
          example: A
        contactPerson:
          type: array
          items:
            properties:
              contactPersonDetails:
                type: object
                properties:
                  contactPerson:
                    type: string
                    example: Gaurav
                  'mobileNumber:':
                    type: string
                    example: '9898989898'
                  email:
                    type: string
                    example: gaurav.sharma@superprocure.com
        kamPerson:
          type: array
          items:
            properties:
              kamPersonDetails:
                type: object
                properties:
                  contactPerson:
                    type: string
                    example: Gaurav
                  'mobileNumber:':
                    type: string
                    example: '9898989898'
                  email:
                    type: string
                    example: gaurav.sharma@superprocure.com
        gstnumber:
          type: string
          example: '12345'
        pannumber:
          type: string
          example: PAN12345